apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: us-central1-docker.pkg.dev/crafty-plateau-456816-g5/gke-docker-repo/backend:latest
          ports:
            - containerPort: 8080  # ✅ changed from 5000 to 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 8080           # ✅ changed from 5000 to 8080
      targetPort: 8080     # ✅ changed from 5000 to 8080
